<%inherit file="/xmas/_nav.mako" />
<%def name="title()">Xmas 2014</%def>
<a href="xmas2014-large.jpg"><img src="xmas2014-small.jpg" alt="[Xmas 2014]" class="center" /></a>

<p>Firstly, apologies for the lack of a Christmas card last year.  We went on an amazing, once in a lifetime holiday instead! We started by flying to Florida for 5 days - highlights included <a href="https://www.kennedyspacecenter.com/">NASA</a>, <a href="http://aquaticabyseaworld.com/">Aquatica</a> and <a href="http://www.gatorland.com/">Gatorland</a> (zip-lining over Alligator swamps!) Next stop, the Caribbean island of <a href="http://www.bequia.net/">Bequia</a> for Christmas and New Year, where colourful boats and unusually named water taxis abound.  We stayed on land but met up with Uncle Pete & Auntie Von on their boat.  Last stop, 2 days in New York. Going from 30°C to -10°C was rather a shock and involved buying a lot more clothes very quickly. Lots of shopping and museums later we returned exhausted to England to go straight back to school.</p>

<p>In April Loveday bought a canal boat - Genevieve - a 45 foot, 30 year old narrow boat. This was supposed to be the antidote to GCSE and A-Level stress but Genevieve has provided quite a lot of excitement of her own, including nearly sinking and producing lots of smoke and conking out en-route to the boat yard! We threw a small surprise party for Amy's 18<sup>th</sup> in May. Amy also passed her driving test and has been annoying her mother ever since by borrowing the car unexpectedly.</p>

<p>In the summer we had a lovely sunny week in Cornwall with friends. The children had so many activities - Quaker youth events, Reading Festival, Yearly Meeting Gathering, One Day Events, etc, etc -  that we couldn't fit in a family holiday, but we did enjoy a few peaceful days on Genevieve with only Dougal and the dog for company.</p>

<p>In September Amy started university at Brunel studying "Digital Design" which is a mixture of creative (eg photography) and technical (eg programming) skills.  Ed (17) survived the whole year with no breakages including an 8 day ski trip with Nick. He started at 6<sup>th</sup> Form College where he is enjoying the freedom from petty school rules.  Isabel (13) spends most of the time sitting in a darkened room lit by her iPad which unfortunately is required for school so can't be confiscated - it's homework, honest! Dougal (7) started his new school and he seems to be settling in well, enjoying playing rugby and football as well as getting stuck into lots of new activities.</p>

<p>In October Loveday's mother, Elizabeth, was diagnosed with pancreatic cancer.  Since then there have been lots of trips to Cornwall and a holiday with the extended family in the Lake District. During the most recent trip to Cornwall, Loveday and the girls left Nick and the boys at home.  The male members of the family decided that a visit to the skate park was in order.  Unfortunately Dougal managed to fall down the big skate ramp and broke his arm rather badly, involving an overnight stay in hospital for Dougal (and Nick). His arm is much better now - cast off on 30<sup>th</sup> December.</p>

<p>This year we celebrated our 20<sup>th</sup> Wedding Anniversary. Loveday has been enjoying patchwork, book groups and <a href="http://en.wikipedia.org/wiki/Nonviolent_Communication">Non-Violent communication</a>. <a href="http://www.memset.com">Memset</a> keeps Nick busy but he just about finds time for an art class and a bit of <a href="https://github.com/ncw">open source programming</a>.</p>

<p>We we look forward to staying on the beach at Polzeath for Christmas and we hope you and yours have a lovely Christmas too.</p>
